In [19]:
%load_ext autoreload

%autoreload 2
import os
import sys
from napari_convpaint.conv_paint_utils import *
from napari_convpaint.conv_paint_model import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
side_len = 8
num_stacks = 3
img = np.array([np.random.randint(4) for a in range(side_len**2 * num_stacks)]).reshape(num_stacks, side_len, side_len)
print(img)

[[[3 1 2 0 1 2 1 3]
  [3 3 2 1 2 2 0 1]
  [1 3 2 2 1 0 1 2]
  [3 2 0 1 1 2 3 0]
  [2 0 2 1 1 2 2 0]
  [3 3 1 2 0 0 0 1]
  [2 0 0 1 0 2 3 3]
  [1 1 0 3 0 2 2 0]]

 [[1 0 3 0 2 1 1 2]
  [0 1 1 0 1 3 2 2]
  [1 2 3 3 3 3 1 3]
  [0 2 3 0 2 1 2 2]
  [3 0 0 3 1 2 3 0]
  [2 0 0 2 2 2 3 1]
  [1 1 0 2 3 1 0 1]
  [0 2 1 0 3 0 2 1]]

 [[0 3 0 1 3 1 2 3]
  [2 3 3 0 2 3 1 2]
  [3 1 2 2 0 0 1 2]
  [2 0 0 2 2 0 2 2]
  [0 1 1 3 1 1 0 1]
  [1 3 2 0 1 0 3 1]
  [2 2 0 1 1 2 3 0]
  [2 3 0 2 0 0 2 1]]]


In [46]:
factor = 3
scaled_img = scale_img(img, factor, use_labels=True)
print(scaled_img)

[[[2 1]
  [0 0]]

 [[3 1]
  [0 2]]

 [[0 0]
  [1 1]]]


In [50]:
rescaled_img = rescale_features(scaled_img, img.shape)
print(rescaled_img[0])

[[1.015625 1.171875 1.171875 1.015625 0.859375 0.703125 0.703125 0.859375]
 [1.421875 1.640625 1.640625 1.421875 1.203125 0.984375 0.984375 1.203125]
 [1.421875 1.640625 1.640625 1.421875 1.203125 0.984375 0.984375 1.203125]
 [1.015625 1.171875 1.171875 1.015625 0.859375 0.703125 0.703125 0.859375]
 [0.609375 0.703125 0.703125 0.609375 0.515625 0.421875 0.421875 0.515625]
 [0.203125 0.234375 0.234375 0.203125 0.171875 0.140625 0.140625 0.171875]
 [0.203125 0.234375 0.234375 0.203125 0.171875 0.140625 0.140625 0.171875]
 [0.609375 0.703125 0.703125 0.609375 0.515625 0.421875 0.421875 0.515625]]


In [51]:
rescaled_img = rescale_class_labels(scaled_img, img.shape)
print(rescaled_img[0])

[[2 2 2 2 1 1 1 1]
 [2 2 2 2 1 1 1 1]
 [2 2 2 2 1 1 1 1]
 [2 2 2 2 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [27]:
img_len = 16
scaling_factor = 3
kernel_size = 3
down_scaled_img = img_len // scaling_factor
scaled_kernel_size = kernel_size * scaling_factor
scaled_padding = (kernel_size // 2) * scaling_factor
padded_with_scaled_kernel = img_len + 2*(scaled_kernel_size//2)
padded_with_scaled_padding = img_len + 2*scaled_padding
down_scaled_padded_with_kernel = padded_with_scaled_kernel // scaling_factor
down_scaled_padded_with_padding = padded_with_scaled_padding // scaling_factor
print("img:", img_len)
print("scaling factor:", scaling_factor)
print("kernel:", kernel_size)
print("downscaled img:", down_scaled_img)
print("downscaled + kernel:", down_scaled_img + 2*(kernel_size//2))
print("scaled kernel:", scaled_kernel_size)
print("padded img:", padded_with_scaled_kernel)
print("with scaled kernel:", down_scaled_padded_with_kernel)
print("with scaled padding:", down_scaled_padded_with_padding)

img: 16
scaling factor: 3
kernel: 3
downscaled img: 5
downscaled + kernel: 7
scaled kernel: 9
padded img: 24
with scaled kernel: 8
with scaled padding: 7


In [24]:
side_len = 80
num_stacks = 3
img = np.array([np.random.randint(4) for a in range(side_len**2 * num_stacks)]).reshape(1, num_stacks, side_len, side_len)
print(img)

[[[[0 1 0 ... 0 3 1]
   [0 3 2 ... 2 2 3]
   [0 0 2 ... 2 1 2]
   ...
   [3 0 0 ... 0 1 3]
   [1 3 1 ... 0 2 3]
   [3 2 1 ... 0 2 2]]

  [[3 2 0 ... 2 0 1]
   [2 3 3 ... 2 0 0]
   [1 0 2 ... 1 1 1]
   ...
   [2 1 2 ... 0 0 1]
   [1 1 3 ... 2 2 0]
   [0 2 0 ... 1 0 0]]

  [[1 2 0 ... 2 1 3]
   [0 1 2 ... 0 3 0]
   [1 3 3 ... 1 3 1]
   ...
   [2 2 0 ... 1 0 3]
   [2 3 3 ... 1 1 0]
   [0 3 2 ... 3 1 1]]]]


In [37]:
kernel_size = (2, 5, 3)
scale_factor = 10
annots = np.zeros(img.shape[1:])
padded_img = pad_for_kernel(img, kernel_size, scale_factor)
padded_annots = pad_for_kernel(annots, kernel_size, scale_factor)
print(padded_img.shape, padded_annots.shape)

(1, 5, 120, 100) (5, 120, 100)


In [55]:
patch_size = (3, 7, 3)
scale_factor = 3
annots = np.zeros(img.shape[1:])
padded_img = pad_to_patch(img, patch_size, scale_factor)
padded_annots = pad_to_patch(annots, patch_size, scale_factor)
print(padded_img.shape, padded_annots.shape)

(1, 3, 84, 81) (3, 84, 81)


In [ ]:
input_scaling = 3
pre_process_stack(img, input_scaling, kernel_size, patch_size, scale_factor).shape

In [10]:
compute_patch_padding((1, 15, 24, 29), (7, 14, 14))

(6, 4, 13)

In [23]:
cp_model = ConvpaintModel()

In [34]:
cp_model.pre_process_list([img])[0].shape
cp_model.pre_process_stack(img).shape

(1, 3, 64, 64)